### ISSUE TITLE
Portainer pulling wrong image & arch for pi-hole

### ISSUE THREAD

**Issue by uhsa779** [portainer/docker-images#4]
When I am trying to pull a pi-hole image via "pihole/pihole:latest" 
It ends up pulling the wrong image. The arch shows amd64 which is incorrect. 

So when I try to get "pihole/pihole:v5.7" instead, it still does that. 

I have tried multiple times to remove the environment variable but that doesn't help. As soon as you deploy the container, it all comes back. 

Talking to the good folks at pihole (pi-hole/docker-pi-hole/issues/805) - I am told that you guys can help in sorting this out. 

Can you guys pls help out with this?

**Comment by uhsa779** [comment]
Is anyone working on this? Need help please...

**Comment by deviantony** [comment]
Hey @uhsa779 

Sorry we have just noticed your problem here, we recommend to open any bug report or feature request directly on the https://github.com/portainer/portainer repository instead.

We were not watching interactions on this repository.

I believe we solved your problem via https://github.com/portainer/portainer/issues/4663 but if you're still having troubles with the Portainer image, feel free to open a new issue in our main repo.
